sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm
install:
  - if [ -n "$GITHUB_OAUTH_TOKEN" ]; then composer config github-oauth.github.com ${GITHUB_OAUTH_TOKEN}; fi;
  - composer update
script:
  - php src/fluid_twig.php
cache:
  directories:
    - $HOME/.composer/cache